### ISSUE TITLE
Some questions for help

### ISSUE THREAD

**Issue by coding9991** [FamiliennameistChow/pred_navi#1]
Thank you for your open source contribution. While using your code, I found that there are no codes related to neural network training, and the pre-trained weights are also incomplete. Do you have any plans to open source these in the future? 
Best wishes.

**Comment by FamiliennameistChow** [comment]
hello, you can get the all of the pre-trained weights from the link: https://pan.baidu.com/s/1dG7Bcq0JU6LaOLRInp_VSA  code: nf7w

or

https://drive.google.com/drive/folders/1ARMpC_ryOBZekh-6TzU0a4sRyP4QcmEF?usp=share_link

**Comment by coding9991** [comment]
Thank you for your response. I will test the weights you provided and the newly committed code. If there are any issues in the future, I will provide feedback to you. 
Thank you again for your excellent work.
